package Server.Model.Network;

public enum RequestType {
    ADD_APPOINTMENT,
    REMOVE_APPOINTMENT,
    LIST_APPOINTMENT_AVAILABILITY,
    BOOK_APPOINTMENT,
    CANCEL_APPOINTMENT,
    SWAP_APPOINTMENT,
    GET_APPOINTMENT_SCHEDULE
}
