package CORBA.Network;


/**
* CORBA.Network/_ServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Saturday, November 23, 2019 4:09:22 o'clock PM EST
*/

public class _ServerStub extends org.omg.CORBA.portable.ObjectImpl implements CORBA.Network.Server
{

  public CORBA.Network.Response AddAppointment (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AddAppointment", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return AddAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // AddAppointment

  public CORBA.Network.Response RemoveAppointment (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("RemoveAppointment", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return RemoveAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // RemoveAppointment

  public CORBA.Network.Response ListAppointmentAvailability (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ListAppointmentAvailability", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ListAppointmentAvailability (request        );
            } finally {
                _releaseReply ($in);
            }
  } // ListAppointmentAvailability

  public CORBA.Network.Response BookAppointment (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("BookAppointment", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return BookAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // BookAppointment

  public CORBA.Network.Response CancelAppointment (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("CancelAppointment", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return CancelAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // CancelAppointment

  public CORBA.Network.Response SwapAppointment (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("SwapAppointment", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return SwapAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // SwapAppointment

  public CORBA.Network.Response GetAppointmentSchedule (CORBA.Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("GetAppointmentSchedule", true);
                CORBA.Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                CORBA.Network.Response $result = CORBA.Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return GetAppointmentSchedule (request        );
            } finally {
                _releaseReply ($in);
            }
  } // GetAppointmentSchedule

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBA.Network/Server:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServerStub
