package CORBA.Network;


/**
* CORBA.Network/AppointmentType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, November 23, 2019 4:09:06 o'clock PM EST
*/

public class AppointmentType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static CORBA.Network.AppointmentType[] __array = new CORBA.Network.AppointmentType [__size];

  public static final int _PHYSICIAN = 0;
  public static final CORBA.Network.AppointmentType PHYSICIAN = new CORBA.Network.AppointmentType(_PHYSICIAN);
  public static final int _SURGEON = 1;
  public static final CORBA.Network.AppointmentType SURGEON = new CORBA.Network.AppointmentType(_SURGEON);
  public static final int _DENTAL = 2;
  public static final CORBA.Network.AppointmentType DENTAL = new CORBA.Network.AppointmentType(_DENTAL);
  public static final int _NONE = 3;
  public static final CORBA.Network.AppointmentType NONE = new CORBA.Network.AppointmentType(_NONE);

  public int value ()
  {
    return __value;
  }

  public static CORBA.Network.AppointmentType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AppointmentType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AppointmentType
