package CORBA.Network;


/**
* CORBA.Network/Appointment.java .
* Generated by the CORBA.IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, October 26, 2019 11:45:54 o'clock PM EDT
*/

public final class Appointment implements org.omg.CORBA.portable.IDLEntity
{
  public CORBA.Network.AppointmentType type = null;
  public String id = null;
  public int maxCapacity = (int)0;
  public String users[] = null;

  public Appointment ()
  {
  } // ctor

  public Appointment (CORBA.Network.AppointmentType _type, String _id, int _maxCapacity, String[] _users)
  {
    type = _type;
    id = _id;
    maxCapacity = _maxCapacity;
    users = _users;
  } // ctor

} // class Appointment
