package CORBA.Network;


/**
* CORBA.Network/AppointmentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, November 23, 2019 4:09:06 o'clock PM EST
*/

abstract public class AppointmentHelper
{
  private static String  _id = "IDL:CORBA.Network/Appointment:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBA.Network.Appointment that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBA.Network.Appointment extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = CORBA.Network.AppointmentTypeHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "maxCapacity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CORBA.Network.UserListHelper.id (), "UserList", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "users",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CORBA.Network.AppointmentHelper.id (), "Appointment", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBA.Network.Appointment read (org.omg.CORBA.portable.InputStream istream)
  {
    CORBA.Network.Appointment value = new CORBA.Network.Appointment ();
    value.type = CORBA.Network.AppointmentTypeHelper.read (istream);
    value.id = istream.read_wstring ();
    value.maxCapacity = istream.read_long ();
    value.users = CORBA.Network.UserListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBA.Network.Appointment value)
  {
    CORBA.Network.AppointmentTypeHelper.write (ostream, value.type);
    ostream.write_wstring (value.id);
    ostream.write_long (value.maxCapacity);
    CORBA.Network.UserListHelper.write (ostream, value.users);
  }

}
