package CORBA.Network;


/**
* CORBA.Network/RequestType.java .
* Generated by the CORBA.IDL-to-Java compiler (portable), version "3.2"
* from Request.idl
* Sunday, October 27, 2019 12:19:24 o'clock AM EDT
*/

public class RequestType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static CORBA.Network.RequestType[] __array = new CORBA.Network.RequestType [__size];

  public static final int _ADD_APPOINTMENT = 0;
  public static final CORBA.Network.RequestType ADD_APPOINTMENT = new CORBA.Network.RequestType(_ADD_APPOINTMENT);
  public static final int _REMOVE_APPOINTMENT = 1;
  public static final CORBA.Network.RequestType REMOVE_APPOINTMENT = new CORBA.Network.RequestType(_REMOVE_APPOINTMENT);
  public static final int _LIST_APPOINTMENT_AVAILABILITY = 2;
  public static final CORBA.Network.RequestType LIST_APPOINTMENT_AVAILABILITY = new CORBA.Network.RequestType(_LIST_APPOINTMENT_AVAILABILITY);
  public static final int _BOOK_APPOINTMENT = 3;
  public static final CORBA.Network.RequestType BOOK_APPOINTMENT = new CORBA.Network.RequestType(_BOOK_APPOINTMENT);
  public static final int _CANCEL_APPOINTMENT = 4;
  public static final CORBA.Network.RequestType CANCEL_APPOINTMENT = new CORBA.Network.RequestType(_CANCEL_APPOINTMENT);
  public static final int _SWAP_APPOINTMENT = 5;
  public static final CORBA.Network.RequestType SWAP_APPOINTMENT = new CORBA.Network.RequestType(_SWAP_APPOINTMENT);
  public static final int _GET_APPOINTMENT_SCHEDULE = 6;
  public static final CORBA.Network.RequestType GET_APPOINTMENT_SCHEDULE = new CORBA.Network.RequestType(_GET_APPOINTMENT_SCHEDULE);

  public int value ()
  {
    return __value;
  }

  public static CORBA.Network.RequestType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected RequestType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class RequestType
