package CORBA.Network;

/**
* CORBA.Network/RequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Request.idl
* Saturday, November 23, 2019 4:09:15 o'clock PM EST
*/

public final class RequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA.Network.RequestType value = null;

  public RequestTypeHolder ()
  {
  }

  public RequestTypeHolder (CORBA.Network.RequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA.Network.RequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA.Network.RequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA.Network.RequestTypeHelper.type ();
  }

}
