package CORBA.Network;


/**
* CORBA.Network/RequestTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Request.idl
* Saturday, November 23, 2019 4:09:15 o'clock PM EST
*/

abstract public class RequestTypeHelper
{
  private static String  _id = "IDL:CORBA.Network/RequestType:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBA.Network.RequestType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBA.Network.RequestType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (CORBA.Network.RequestTypeHelper.id (), "RequestType", new String[] { "ADD_APPOINTMENT", "REMOVE_APPOINTMENT", "LIST_APPOINTMENT_AVAILABILITY", "BOOK_APPOINTMENT", "CANCEL_APPOINTMENT", "SWAP_APPOINTMENT", "GET_APPOINTMENT_SCHEDULE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBA.Network.RequestType read (org.omg.CORBA.portable.InputStream istream)
  {
    return CORBA.Network.RequestType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBA.Network.RequestType value)
  {
    ostream.write_long (value.value ());
  }

}
