package CORBA.Network;

/**
* CORBA.Network/RequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Request.idl
* Saturday, November 23, 2019 4:09:15 o'clock PM EST
*/

public final class RequestHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA.Network.Request value = null;

  public RequestHolder ()
  {
  }

  public RequestHolder (CORBA.Network.Request initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA.Network.RequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA.Network.RequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA.Network.RequestHelper.type ();
  }

}
