package CORBA.Network;


/**
* CORBA.Network/ResponseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Response.idl
* Saturday, November 23, 2019 4:09:19 o'clock PM EST
*/

abstract public class ResponseHelper
{
  private static String  _id = "IDL:CORBA.Network/Response:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBA.Network.Response that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBA.Network.Response extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[0] = new org.omg.CORBA.StructMember (
            "success",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "message",
            _tcOf_members0,
            null);
          _tcOf_members0 = CORBA.Network.AppointmentHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CORBA.Network.AppointmentListHelper.id (), "AppointmentList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "appointments",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CORBA.Network.ResponseHelper.id (), "Response", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBA.Network.Response read (org.omg.CORBA.portable.InputStream istream)
  {
    CORBA.Network.Response value = new CORBA.Network.Response ();
    value.success = istream.read_boolean ();
    value.message = istream.read_wstring ();
    value.appointments = CORBA.Network.AppointmentListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBA.Network.Response value)
  {
    ostream.write_boolean (value.success);
    ostream.write_wstring (value.message);
    CORBA.Network.AppointmentListHelper.write (ostream, value.appointments);
  }

}
