package CORBA.Network;

/**
* CORBA.Network/ResponseHolder.java .
* Generated by the CORBA.IDL-to-Java compiler (portable), version "3.2"
* from Response.idl
* Thursday, October 24, 2019 12:38:17 o'clock AM EDT
*/

public final class ResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA.Network.Response value = null;

  public ResponseHolder ()
  {
  }

  public ResponseHolder (CORBA.Network.Response initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA.Network.ResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA.Network.ResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA.Network.ResponseHelper.type ();
  }

}
