package CORBA.Network;


/**
* CORBA.Network/Response.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Response.idl
* Saturday, November 23, 2019 4:09:19 o'clock PM EST
*/

public final class Response implements org.omg.CORBA.portable.IDLEntity
{
  public boolean success = false;
  public String message = null;
  public CORBA.Network.Appointment appointments[] = null;

  public Response ()
  {
  } // ctor

  public Response (boolean _success, String _message, CORBA.Network.Appointment[] _appointments)
  {
    success = _success;
    message = _message;
    appointments = _appointments;
  } // ctor

} // class Response
