package CORBA.Network;


/**
* CORBA.Network/Server.java .
* Generated by the CORBA.IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, October 24, 2019 12:38:20 o'clock AM EDT
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
