package CORBA.Network;

/**
* CORBA.Network/ServerHolder.java .
* Generated by the CORBA.IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, October 24, 2019 12:38:20 o'clock AM EDT
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA.Network.Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (CORBA.Network.Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA.Network.ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA.Network.ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA.Network.ServerHelper.type ();
  }

}
