package CORBA.Network;


/**
* CORBA.Network/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Saturday, November 23, 2019 4:09:22 o'clock PM EST
*/

public interface ServerOperations 
{
  CORBA.Network.Response AddAppointment (CORBA.Network.Request request);
  CORBA.Network.Response RemoveAppointment (CORBA.Network.Request request);
  CORBA.Network.Response ListAppointmentAvailability (CORBA.Network.Request request);
  CORBA.Network.Response BookAppointment (CORBA.Network.Request request);
  CORBA.Network.Response CancelAppointment (CORBA.Network.Request request);
  CORBA.Network.Response SwapAppointment (CORBA.Network.Request request);
  CORBA.Network.Response GetAppointmentSchedule (CORBA.Network.Request request);
} // interface ServerOperations
