package CORBA.Network;


/**
* CORBA.Network/ServerOperations.java .
* Generated by the CORBA.IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, October 24, 2019 12:38:20 o'clock AM EDT
*/

public interface ServerOperations 
{
  CORBA.Network.Response AddAppointment (CORBA.Network.Request request);
  CORBA.Network.Response RemoveAppointment (CORBA.Network.Request request);
  CORBA.Network.Response ListAppointmentAvailability (CORBA.Network.Request request);
  CORBA.Network.Response BookAppointment (CORBA.Network.Request request);
  CORBA.Network.Response CancelAppointment (CORBA.Network.Request request);
  CORBA.Network.Response SwapAppointment (CORBA.Network.Request request);
  CORBA.Network.Response GetAppointmentSchedule (CORBA.Network.Request request);
  String GetFullID (String id);
} // interface ServerOperations
