package CORBA.Network;


/**
* CORBA.Network/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Saturday, November 23, 2019 4:09:22 o'clock PM EST
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
