package CORBA.Network;


/**
* CORBA.Network/UserListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, November 23, 2019 4:09:06 o'clock PM EST
*/

public final class UserListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public UserListHolder ()
  {
  }

  public UserListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA.Network.UserListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA.Network.UserListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA.Network.UserListHelper.type ();
  }

}
