package Network;


/**
* Network/_ServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, October 24, 2019 12:38:20 o'clock AM EDT
*/

public class _ServerStub extends org.omg.CORBA.portable.ObjectImpl implements Network.Server
{

  public Network.Response AddAppointment (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AddAppointment", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return AddAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // AddAppointment

  public Network.Response RemoveAppointment (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("RemoveAppointment", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return RemoveAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // RemoveAppointment

  public Network.Response ListAppointmentAvailability (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ListAppointmentAvailability", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ListAppointmentAvailability (request        );
            } finally {
                _releaseReply ($in);
            }
  } // ListAppointmentAvailability

  public Network.Response BookAppointment (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("BookAppointment", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return BookAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // BookAppointment

  public Network.Response CancelAppointment (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("CancelAppointment", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return CancelAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // CancelAppointment

  public Network.Response SwapAppointment (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("SwapAppointment", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return SwapAppointment (request        );
            } finally {
                _releaseReply ($in);
            }
  } // SwapAppointment

  public Network.Response GetAppointmentSchedule (Network.Request request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("GetAppointmentSchedule", true);
                Network.RequestHelper.write ($out, request);
                $in = _invoke ($out);
                Network.Response $result = Network.ResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return GetAppointmentSchedule (request        );
            } finally {
                _releaseReply ($in);
            }
  } // GetAppointmentSchedule

  public String GetFullID (String id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("GetFullID", true);
                $out.write_wstring (id);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return GetFullID (id        );
            } finally {
                _releaseReply ($in);
            }
  } // GetFullID

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Network/Server:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServerStub
