package Network;


/**
* Network/AppointmentListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Response.idl
* Thursday, October 24, 2019 12:38:17 o'clock AM EDT
*/

public final class AppointmentListHolder implements org.omg.CORBA.portable.Streamable
{
  public Network.Appointment value[] = null;

  public AppointmentListHolder ()
  {
  }

  public AppointmentListHolder (Network.Appointment[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Network.AppointmentListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Network.AppointmentListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Network.AppointmentListHelper.type ();
  }

}
