package Network;

/**
* Network/AppointmentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, October 26, 2019 11:45:54 o'clock PM EDT
*/

public final class AppointmentHolder implements org.omg.CORBA.portable.Streamable
{
  public Network.Appointment value = null;

  public AppointmentHolder ()
  {
  }

  public AppointmentHolder (Network.Appointment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Network.AppointmentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Network.AppointmentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Network.AppointmentHelper.type ();
  }

}
