package Network;


/**
* Network/AppointmentType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, October 26, 2019 11:45:54 o'clock PM EDT
*/

public class AppointmentType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static Network.AppointmentType[] __array = new Network.AppointmentType [__size];

  public static final int _PHYSICIAN = 0;
  public static final Network.AppointmentType PHYSICIAN = new Network.AppointmentType(_PHYSICIAN);
  public static final int _SURGEON = 1;
  public static final Network.AppointmentType SURGEON = new Network.AppointmentType(_SURGEON);
  public static final int _DENTAL = 2;
  public static final Network.AppointmentType DENTAL = new Network.AppointmentType(_DENTAL);
  public static final int _NONE = 3;
  public static final Network.AppointmentType NONE = new Network.AppointmentType(_NONE);

  public int value ()
  {
    return __value;
  }

  public static Network.AppointmentType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AppointmentType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AppointmentType
