package Network;

/**
* Network/RequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Request.idl
* Sunday, October 27, 2019 12:19:24 o'clock AM EDT
*/

public final class RequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public Network.RequestType value = null;

  public RequestTypeHolder ()
  {
  }

  public RequestTypeHolder (Network.RequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Network.RequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Network.RequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Network.RequestTypeHelper.type ();
  }

}
