package Network;

/**
* Network/RequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Request.idl
* Sunday, October 27, 2019 12:19:24 o'clock AM EDT
*/

public final class RequestHolder implements org.omg.CORBA.portable.Streamable
{
  public Network.Request value = null;

  public RequestHolder ()
  {
  }

  public RequestHolder (Network.Request initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Network.RequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Network.RequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Network.RequestHelper.type ();
  }

}
