package Network;

/**
* Network/ResponseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Response.idl
* Thursday, October 24, 2019 12:38:17 o'clock AM EDT
*/

public final class ResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public Network.Response value = null;

  public ResponseHolder ()
  {
  }

  public ResponseHolder (Network.Response initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Network.ResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Network.ResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Network.ResponseHelper.type ();
  }

}
