package Network;


/**
* Network/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, October 24, 2019 12:38:20 o'clock AM EDT
*/

public interface ServerOperations 
{
  Network.Response AddAppointment (Network.Request request);
  Network.Response RemoveAppointment (Network.Request request);
  Network.Response ListAppointmentAvailability (Network.Request request);
  Network.Response BookAppointment (Network.Request request);
  Network.Response CancelAppointment (Network.Request request);
  Network.Response SwapAppointment (Network.Request request);
  Network.Response GetAppointmentSchedule (Network.Request request);
  String GetFullID (String id);
} // interface ServerOperations
