package Network;


/**
* Network/UserListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointment.idl
* Saturday, October 26, 2019 11:45:54 o'clock PM EDT
*/

public final class UserListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public UserListHolder ()
  {
  }

  public UserListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Network.UserListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Network.UserListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Network.UserListHelper.type ();
  }

}
